export const POST_ADDED = "POST_ADDED";
export const POST_ADDED_TO_MY_GROUP = "POST_ADDED_TO_MY_GROUP";
export const COMMENT_ADDED = "COMMENT_ADDED";
export const MESSAGE_ADDED = "MESSAGE_ADDED";
export const TOGGLE_USER_JOINED = "TOGGLE_USER_JOINED";
export const CHAT_MEMBER_ADDED = "CHAT_MEMBER_ADDED";
export const GROUP_MEMBER_ADDED = "GROUP_MEMBER_ADDED";
export const NOTIFICATION_ADDED = "NOTIFICATION_ADDED";
export const NOTIFICATION_DELETED = "NOTIFICATION_DELETED";
export const FRIEND_REQUEST_NOTIFICATION_ADDED =
	"FRIEND_REQUEST_NOTIFICATION_ADDED";
export const GROUP_INVITE_NOTIFICATION_ADDED =
	"GROUP_INVITE_NOTIFICATION_ADDED";
